//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnivoreClassLibraryTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JSONStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JSONStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OmnivoreClassLibraryTests.JSONStrings", typeof(JSONStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;employee&quot;: {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;934d3a9ae389e3279fd443cdb05f80cc&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/BdTaKT4X/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_retrieve&quot;}}, &quot;check_name&quot;: &quot;Bob&quot;, &quot;first_name&quot;: &quot;Bob&quot;, &quot;id&quot;: &quot;BdTaKT4X&quot;, &quot;last_name&quot;: &quot;Belcher&quot;, &quot;login&quot;: &quot;100&quot;}, &quot;items&quot;: [{&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;menu_item&quot;: {&quot;_links&quot;: {&quot;modifier_groups&quot;: {&quot;etag&quot;: &quot;ebbcdef0a0dc1c09f4ac530780a7beb6&quot;, &quot;href&quot;: &quot;https://api.omn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AddTicketItemsResponse {
            get {
                return ResourceManager.GetString("AddTicketItemsResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_links&quot;: {&quot;self&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/&quot;}}, &quot;versions&quot;: [{&quot;deprecation_date&quot;: null, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/&quot;, &quot;major&quot;: 0, &quot;minor&quot;: 1, &quot;release_date&quot;: &quot;2013-01-01&quot;, &quot;retirement_date&quot;: null, &quot;status&quot;: &quot;alpha&quot;}]}.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_links&quot;: {&quot;discounts&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/discounts/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#discount_list&quot;}, &quot;employees&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_list&quot;}, &quot;menu&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#menu&quot;}, &quot;order_types&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/order_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultLocation {
            get {
                return ResourceManager.GetString("DefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;employees&quot;: [{&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;dedf230a0b8b6dd7aff12d4698de7dee&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/MjikgioG/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_retrieve&quot;}}, &quot;check_name&quot;: &quot;Louise&quot;, &quot;first_name&quot;: &quot;Louise&quot;, &quot;id&quot;: &quot;MjikgioG&quot;, &quot;last_name&quot;: &quot;Belcher&quot;, &quot;login&quot;: &quot;666&quot;}, {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;934d3a9ae389e3279fd443cdb05f80cc&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/BdTaKT4X/&quot;, &quot;profile&quot;: &quot;https://p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;locations&quot;: [{&quot;_links&quot;: {&quot;discounts&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/discounts/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#discount_list&quot;}, &quot;employees&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_list&quot;}, &quot;menu&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#menu&quot;}, &quot;order_types&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_links&quot;: {&quot;categories&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/categories/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#category_list&quot;}, &quot;items&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/items/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#menu-item_list&quot;}, &quot;modifiers&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/modifiers/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#modifier_list&quot;}, &quot;self&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/loc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;categories&quot;: [{&quot;_embedded&quot;: {&quot;items&quot;: [{&quot;_links&quot;: {&quot;modifier_groups&quot;: {&quot;etag&quot;: &quot;d41d8cd98f00b204e9800998ecf8427e&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/items/gki84ia9/modifier_groups/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#modifier-group_list&quot;}, &quot;self&quot;: {&quot;etag&quot;: &quot;7554da25fdabb02e0280ce2838818418&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/items/gki84ia9/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#menu-item_retrieve&quot;}}, &quot;id&quot;: &quot;gki84ia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MenuCategories {
            get {
                return ResourceManager.GetString("MenuCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;modifier_groups&quot;: [{&quot;_embedded&quot;: {&quot;options&quot;: [{&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;029af5bbe3172a8eba4177fbe6adba31&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/menu/modifiers/8kT9KTX7/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#modifier_retrieve&quot;}}, &quot;id&quot;: &quot;8kT9KTX7&quot;, &quot;name&quot;: &quot;Perfect&quot;, &quot;price_levels&quot;: [{&quot;id&quot;: &quot;nAceac8B&quot;, &quot;price&quot;: 0}], &quot;price_per_unit&quot;: 0}, {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;ea121f5c8a6fb7715c5812ef8ee7c514&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/men [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MenuItemModifierGroups {
            get {
                return ResourceManager.GetString("MenuItemModifierGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;employee&quot;: {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;934d3a9ae389e3279fd443cdb05f80cc&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/BdTaKT4X/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_retrieve&quot;}}, &quot;check_name&quot;: &quot;Bob&quot;, &quot;first_name&quot;: &quot;Bob&quot;, &quot;id&quot;: &quot;BdTaKT4X&quot;, &quot;last_name&quot;: &quot;Belcher&quot;, &quot;login&quot;: &quot;100&quot;}, &quot;items&quot;: [], &quot;order_type&quot;: {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;f734af98716581abbfd84b0fc068ade7&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/order_t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenTicketResponse {
            get {
                return ResourceManager.GetString("OpenTicketResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;order_types&quot;: [{&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;f734af98716581abbfd84b0fc068ade7&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/order_types/KxiAaip5/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#order-type_retrieve&quot;}}, &quot;available&quot;: true, &quot;id&quot;: &quot;KxiAaip5&quot;, &quot;name&quot;: &quot;Eat In&quot;}, {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;fec7d96848d0cb4cdceb7ef24ce6c0d0&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/order_types/jLTqoTba/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#order-type_retrie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderTypes {
            get {
                return ResourceManager.GetString("OrderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;amount_paid&quot;: 2153,&quot;accepted&quot;: true,&quot;ticket_closed&quot;: true,&quot;balance_remaining&quot;: 0,&quot;type&quot;: &quot;card_present&quot;}.
        /// </summary>
        internal static string PaymentStatusResponse {
            get {
                return ResourceManager.GetString("PaymentStatusResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;revenue_centers&quot;: [{&quot;_embedded&quot;: {&quot;open_tickets&quot;: [{&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;employee&quot;: {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;dedf230a0b8b6dd7aff12d4698de7dee&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/MjikgioG/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_retrieve&quot;}}, &quot;check_name&quot;: &quot;Louise&quot;, &quot;first_name&quot;: &quot;Louise&quot;, &quot;id&quot;: &quot;MjikgioG&quot;, &quot;last_name&quot;: &quot;Belcher&quot;, &quot;login&quot;: &quot;666&quot;}, &quot;items&quot;: [{&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;menu_item&quot;: {&quot;_links&quot;: {&quot;modifier_group [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RevenueCenters {
            get {
                return ResourceManager.GetString("RevenueCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;tables&quot;: [{&quot;_embedded&quot;: {&quot;open_tickets&quot;: [{&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;employee&quot;: {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;dedf230a0b8b6dd7aff12d4698de7dee&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/MjikgioG/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_retrieve&quot;}}, &quot;check_name&quot;: &quot;Louise&quot;, &quot;first_name&quot;: &quot;Louise&quot;, &quot;id&quot;: &quot;MjikgioG&quot;, &quot;last_name&quot;: &quot;Belcher&quot;, &quot;login&quot;: &quot;666&quot;}, &quot;items&quot;: [{&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;menu_item&quot;: {&quot;_links&quot;: {&quot;modifier_groups&quot;: {&quot;eta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;tender_types&quot;: [{&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;9657475f018883c0446aa942afe38779&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/tender_types/zoc5KcBo/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#tender-type_retrieve&quot;}}, &quot;id&quot;: &quot;zoc5KcBo&quot;, &quot;name&quot;: &quot;Gift Card&quot;}, {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;13b936cf004bda4730c2e91ed926b745&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/tender_types/LgiKji9a/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#tender-type_retrieve&quot;}}, &quot;id&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TenderTypes {
            get {
                return ResourceManager.GetString("TenderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;employee&quot;: {&quot;_links&quot;: {&quot;self&quot;: {&quot;etag&quot;: &quot;dedf230a0b8b6dd7aff12d4698de7dee&quot;, &quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/zGibgKT9/employees/MjikgioG/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#employee_retrieve&quot;}}, &quot;check_name&quot;: &quot;Louise&quot;, &quot;first_name&quot;: &quot;Louise&quot;, &quot;id&quot;: &quot;MjikgioG&quot;, &quot;last_name&quot;: &quot;Belcher&quot;, &quot;login&quot;: &quot;666&quot;}, &quot;items&quot;: [{&quot;_embedded&quot;: {&quot;discounts&quot;: [], &quot;menu_item&quot;: {&quot;_links&quot;: {&quot;modifier_groups&quot;: {&quot;etag&quot;: &quot;ebbcdef0a0dc1c09f4ac530780a7beb6&quot;, &quot;href&quot;: &quot;https://a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;_links&quot;: {&quot;activate&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/activate/&quot;}, &quot;locations&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/locations/&quot;, &quot;profile&quot;: &quot;https://panel.omnivore.io/docs/api#location_list&quot;}, &quot;self&quot;: {&quot;href&quot;: &quot;https://api.omnivore.io/0.1/&quot;}}}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
